// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package handler

import (
	"github.com/grpc-shop/user-srv/dao"
	"github.com/grpc-shop/user-srv/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserHandler(db *gorm.DB) *UserHandler {
	userDao := dao.NewUserImpl(db)
	userServer := service.NewUserServer(userDao)
	userHandler := NewUserHandler(userServer)
	return userHandler
}
